#
# Automatically generated file. DO NOT MODIFY
#

PRODUCT_SOONG_NAMESPACES += \
    vendor/lenovo/tb373fu

PRODUCT_COPY_FILES += \
    vendor/lenovo/tb373fu/proprietary/system/etc/public.libraries-mtk.txt:$(TARGET_COPY_OUT_SYSTEM)/etc/public.libraries-mtk.txt \
    vendor/lenovo/tb373fu/proprietary/system_ext/etc/permissions/com.android.hotwordenrollment.common.util.xml:$(TARGET_COPY_OUT_SYSTEM_EXT)/etc/permissions/com.android.hotwordenrollment.common.util.xml \
    vendor/lenovo/tb373fu/proprietary/vendor/bin/crossbuild/DataSet/SQLiteModule/db/ae/mt6897/ParameterDB_ae.db:$(TARGET_COPY_OUT_VENDOR)/bin/crossbuild/DataSet/SQLiteModule/db/ae/mt6897/ParameterDB_ae.db \
    vendor/lenovo/tb373fu/proprietary/vendor/bin/crossbuild/DataSet/SQLiteModule/db/af/mt6897/ParameterDB_af.db:$(TARGET_COPY_OUT_VENDOR)/bin/crossbuild/DataSet/SQLiteModule/db/af/mt6897/ParameterDB_af.db \
    vendor/lenovo/tb373fu/proprietary/vendor/bin/crossbuild/DataSet/SQLiteModule/db/awb/mt6897/ParameterDB_awb.db:$(TARGET_COPY_OUT_VENDOR)/bin/crossbuild/DataSet/SQLiteModule/db/awb/mt6897/ParameterDB_awb.db \
    vendor/lenovo/tb373fu/proprietary/vendor/bin/crossbuild/DataSet/SQLiteModule/db/awbsync/mt6897/ParameterDB_awbsync.db:$(TARGET_COPY_OUT_VENDOR)/bin/crossbuild/DataSet/SQLiteModule/db/awbsync/mt6897/ParameterDB_awbsync.db \
    vendor/lenovo/tb373fu/proprietary/vendor/bin/crossbuild/DataSet/SQLiteModule/db/feature/mt6897/ParameterDB_feature.db:$(TARGET_COPY_OUT_VENDOR)/bin/crossbuild/DataSet/SQLiteModule/db/feature/mt6897/ParameterDB_feature.db \
    vendor/lenovo/tb373fu/proprietary/vendor/bin/crossbuild/DataSet/SQLiteModule/db/flash/mt6897/ParameterDB_flash.db:$(TARGET_COPY_OUT_VENDOR)/bin/crossbuild/DataSet/SQLiteModule/db/flash/mt6897/ParameterDB_flash.db \
    vendor/lenovo/tb373fu/proprietary/vendor/bin/crossbuild/DataSet/SQLiteModule/db/flashcali/mt6897/ParameterDB_flashcali.db:$(TARGET_COPY_OUT_VENDOR)/bin/crossbuild/DataSet/SQLiteModule/db/flashcali/mt6897/ParameterDB_flashcali.db \
    vendor/lenovo/tb373fu/proprietary/vendor/bin/crossbuild/DataSet/SQLiteModule/db/mt6897/ParameterDB.db:$(TARGET_COPY_OUT_VENDOR)/bin/crossbuild/DataSet/SQLiteModule/db/mt6897/ParameterDB.db \
    vendor/lenovo/tb373fu/proprietary/vendor/bin/crossbuild/DataSet/SQLiteModule/db/mt6897/sw_top_control_data.db:$(TARGET_COPY_OUT_VENDOR)/bin/crossbuild/DataSet/SQLiteModule/db/mt6897/sw_top_control_data.db \
    vendor/lenovo/tb373fu/proprietary/vendor/bin/crossbuild/DataSet/SQLiteModule/db/mt6897/top_control_data.db:$(TARGET_COPY_OUT_VENDOR)/bin/crossbuild/DataSet/SQLiteModule/db/mt6897/top_control_data.db \
    vendor/lenovo/tb373fu/proprietary/vendor/bin/crossbuild/DataSet/SQLiteModule/db/pd/mt6897/ParameterDB_pd.db:$(TARGET_COPY_OUT_VENDOR)/bin/crossbuild/DataSet/SQLiteModule/db/pd/mt6897/ParameterDB_pd.db \
    vendor/lenovo/tb373fu/proprietary/vendor/bin/crossbuild/DataSet/SQLiteModule/db/pipeline/mt6897/ParameterDB_pipeline.db:$(TARGET_COPY_OUT_VENDOR)/bin/crossbuild/DataSet/SQLiteModule/db/pipeline/mt6897/ParameterDB_pipeline.db \
    vendor/lenovo/tb373fu/proprietary/vendor/bin/crossbuild/DataSet/SQLiteModule/db/port_select.db:$(TARGET_COPY_OUT_VENDOR)/bin/crossbuild/DataSet/SQLiteModule/db/port_select.db \
    vendor/lenovo/tb373fu/proprietary/vendor/bin/crossbuild/DataSet/SQLiteModule/db/tone/mt6897/ParameterDB_tone.db:$(TARGET_COPY_OUT_VENDOR)/bin/crossbuild/DataSet/SQLiteModule/db/tone/mt6897/ParameterDB_tone.db \
    vendor/lenovo/tb373fu/proprietary/vendor/bin/crossbuild/DataSet/SQLiteModule/db/tuning_DB/default_sensor/mt6897/ISP_mapping.db:$(TARGET_COPY_OUT_VENDOR)/bin/crossbuild/DataSet/SQLiteModule/db/tuning_DB/default_sensor/mt6897/ISP_mapping.db \
    vendor/lenovo/tb373fu/proprietary/vendor/bin/crossbuild/DataSet/SQLiteModule/db/tuning_DB/default_sensor/mt6897/ISP_param.db:$(TARGET_COPY_OUT_VENDOR)/bin/crossbuild/DataSet/SQLiteModule/db/tuning_DB/default_sensor/mt6897/ISP_param.db \
    vendor/lenovo/tb373fu/proprietary/vendor/bin/crossbuild/DataSet/SQLiteModule/db/tuning_DB/gc13a0_mipi_raw/mt6897/ISP_mapping.db:$(TARGET_COPY_OUT_VENDOR)/bin/crossbuild/DataSet/SQLiteModule/db/tuning_DB/gc13a0_mipi_raw/mt6897/ISP_mapping.db \
    vendor/lenovo/tb373fu/proprietary/vendor/bin/crossbuild/DataSet/SQLiteModule/db/tuning_DB/gc13a0_mipi_raw/mt6897/ISP_param.db:$(TARGET_COPY_OUT_VENDOR)/bin/crossbuild/DataSet/SQLiteModule/db/tuning_DB/gc13a0_mipi_raw/mt6897/ISP_param.db \
    vendor/lenovo/tb373fu/proprietary/vendor/bin/crossbuild/DataSet/SQLiteModule/db/tuning_DB/imx214_mipi_raw/mt6897/ISP_mapping.db:$(TARGET_COPY_OUT_VENDOR)/bin/crossbuild/DataSet/SQLiteModule/db/tuning_DB/imx214_mipi_raw/mt6897/ISP_mapping.db \
    vendor/lenovo/tb373fu/proprietary/vendor/bin/crossbuild/DataSet/SQLiteModule/db/tuning_DB/imx214_mipi_raw/mt6897/ISP_param.db:$(TARGET_COPY_OUT_VENDOR)/bin/crossbuild/DataSet/SQLiteModule/db/tuning_DB/imx214_mipi_raw/mt6897/ISP_param.db \
    vendor/lenovo/tb373fu/proprietary/vendor/bin/crossbuild/DataSet/SQLiteModule/db/tuning_DB/imx334_mipi_raw/mt6897/ISP_mapping.db:$(TARGET_COPY_OUT_VENDOR)/bin/crossbuild/DataSet/SQLiteModule/db/tuning_DB/imx334_mipi_raw/mt6897/ISP_mapping.db \
    vendor/lenovo/tb373fu/proprietary/vendor/bin/crossbuild/DataSet/SQLiteModule/db/tuning_DB/imx334_mipi_raw/mt6897/ISP_param.db:$(TARGET_COPY_OUT_VENDOR)/bin/crossbuild/DataSet/SQLiteModule/db/tuning_DB/imx334_mipi_raw/mt6897/ISP_param.db \
    vendor/lenovo/tb373fu/proprietary/vendor/bin/crossbuild/DataSet/SQLiteModule/db/tuning_DB/imx334sub_mipi_raw/mt6897/ISP_mapping.db:$(TARGET_COPY_OUT_VENDOR)/bin/crossbuild/DataSet/SQLiteModule/db/tuning_DB/imx334sub_mipi_raw/mt6897/ISP_mapping.db \
    vendor/lenovo/tb373fu/proprietary/vendor/bin/crossbuild/DataSet/SQLiteModule/db/tuning_DB/imx334sub_mipi_raw/mt6897/ISP_param.db:$(TARGET_COPY_OUT_VENDOR)/bin/crossbuild/DataSet/SQLiteModule/db/tuning_DB/imx334sub_mipi_raw/mt6897/ISP_param.db \
    vendor/lenovo/tb373fu/proprietary/vendor/bin/crossbuild/DataSet/SQLiteModule/db/tuning_DB/imx481_mipi_raw/mt6897/ISP_mapping.db:$(TARGET_COPY_OUT_VENDOR)/bin/crossbuild/DataSet/SQLiteModule/db/tuning_DB/imx481_mipi_raw/mt6897/ISP_mapping.db \
    vendor/lenovo/tb373fu/proprietary/vendor/bin/crossbuild/DataSet/SQLiteModule/db/tuning_DB/imx481_mipi_raw/mt6897/ISP_param.db:$(TARGET_COPY_OUT_VENDOR)/bin/crossbuild/DataSet/SQLiteModule/db/tuning_DB/imx481_mipi_raw/mt6897/ISP_param.db \
    vendor/lenovo/tb373fu/proprietary/vendor/bin/crossbuild/DataSet/SQLiteModule/db/tuning_DB/imx499_mipi_raw/mt6897/ISP_mapping.db:$(TARGET_COPY_OUT_VENDOR)/bin/crossbuild/DataSet/SQLiteModule/db/tuning_DB/imx499_mipi_raw/mt6897/ISP_mapping.db \
    vendor/lenovo/tb373fu/proprietary/vendor/bin/crossbuild/DataSet/SQLiteModule/db/tuning_DB/imx499_mipi_raw/mt6897/ISP_param.db:$(TARGET_COPY_OUT_VENDOR)/bin/crossbuild/DataSet/SQLiteModule/db/tuning_DB/imx499_mipi_raw/mt6897/ISP_param.db \
    vendor/lenovo/tb373fu/proprietary/vendor/bin/crossbuild/DataSet/SQLiteModule/db/tuning_DB/imx586_mipi_raw/mt6897/ISP_mapping.db:$(TARGET_COPY_OUT_VENDOR)/bin/crossbuild/DataSet/SQLiteModule/db/tuning_DB/imx586_mipi_raw/mt6897/ISP_mapping.db \
    vendor/lenovo/tb373fu/proprietary/vendor/bin/crossbuild/DataSet/SQLiteModule/db/tuning_DB/imx586_mipi_raw/mt6897/ISP_param.db:$(TARGET_COPY_OUT_VENDOR)/bin/crossbuild/DataSet/SQLiteModule/db/tuning_DB/imx586_mipi_raw/mt6897/ISP_param.db \
    vendor/lenovo/tb373fu/proprietary/vendor/bin/crossbuild/DataSet/SQLiteModule/db/tuning_DB/imx709_mipi_raw/mt6897/ISP_mapping.db:$(TARGET_COPY_OUT_VENDOR)/bin/crossbuild/DataSet/SQLiteModule/db/tuning_DB/imx709_mipi_raw/mt6897/ISP_mapping.db \
    vendor/lenovo/tb373fu/proprietary/vendor/bin/crossbuild/DataSet/SQLiteModule/db/tuning_DB/imx709_mipi_raw/mt6897/ISP_param.db:$(TARGET_COPY_OUT_VENDOR)/bin/crossbuild/DataSet/SQLiteModule/db/tuning_DB/imx709_mipi_raw/mt6897/ISP_param.db \
    vendor/lenovo/tb373fu/proprietary/vendor/bin/crossbuild/DataSet/SQLiteModule/db/tuning_DB/imx709o_mipi_raw/mt6897/ISP_mapping.db:$(TARGET_COPY_OUT_VENDOR)/bin/crossbuild/DataSet/SQLiteModule/db/tuning_DB/imx709o_mipi_raw/mt6897/ISP_mapping.db \
    vendor/lenovo/tb373fu/proprietary/vendor/bin/crossbuild/DataSet/SQLiteModule/db/tuning_DB/imx709o_mipi_raw/mt6897/ISP_param.db:$(TARGET_COPY_OUT_VENDOR)/bin/crossbuild/DataSet/SQLiteModule/db/tuning_DB/imx709o_mipi_raw/mt6897/ISP_param.db \
    vendor/lenovo/tb373fu/proprietary/vendor/bin/crossbuild/DataSet/SQLiteModule/db/tuning_DB/imx766_mipi_raw/mt6897/ISP_mapping.db:$(TARGET_COPY_OUT_VENDOR)/bin/crossbuild/DataSet/SQLiteModule/db/tuning_DB/imx766_mipi_raw/mt6897/ISP_mapping.db \
    vendor/lenovo/tb373fu/proprietary/vendor/bin/crossbuild/DataSet/SQLiteModule/db/tuning_DB/imx766_mipi_raw/mt6897/ISP_param.db:$(TARGET_COPY_OUT_VENDOR)/bin/crossbuild/DataSet/SQLiteModule/db/tuning_DB/imx766_mipi_raw/mt6897/ISP_param.db \
    vendor/lenovo/tb373fu/proprietary/vendor/bin/crossbuild/DataSet/SQLiteModule/db/tuning_DB/imx766dual_mipi_raw/mt6897/ISP_mapping.db:$(TARGET_COPY_OUT_VENDOR)/bin/crossbuild/DataSet/SQLiteModule/db/tuning_DB/imx766dual_mipi_raw/mt6897/ISP_mapping.db \
    vendor/lenovo/tb373fu/proprietary/vendor/bin/crossbuild/DataSet/SQLiteModule/db/tuning_DB/imx766dual_mipi_raw/mt6897/ISP_param.db:$(TARGET_COPY_OUT_VENDOR)/bin/crossbuild/DataSet/SQLiteModule/db/tuning_DB/imx766dual_mipi_raw/mt6897/ISP_param.db \
    vendor/lenovo/tb373fu/proprietary/vendor/bin/crossbuild/DataSet/SQLiteModule/db/tuning_DB/imx766dualo_mipi_raw/mt6897/ISP_mapping.db:$(TARGET_COPY_OUT_VENDOR)/bin/crossbuild/DataSet/SQLiteModule/db/tuning_DB/imx766dualo_mipi_raw/mt6897/ISP_mapping.db \
    vendor/lenovo/tb373fu/proprietary/vendor/bin/crossbuild/DataSet/SQLiteModule/db/tuning_DB/imx766dualo_mipi_raw/mt6897/ISP_param.db:$(TARGET_COPY_OUT_VENDOR)/bin/crossbuild/DataSet/SQLiteModule/db/tuning_DB/imx766dualo_mipi_raw/mt6897/ISP_param.db \
    vendor/lenovo/tb373fu/proprietary/vendor/bin/crossbuild/DataSet/SQLiteModule/db/tuning_DB/imx766o_mipi_raw/mt6897/ISP_mapping.db:$(TARGET_COPY_OUT_VENDOR)/bin/crossbuild/DataSet/SQLiteModule/db/tuning_DB/imx766o_mipi_raw/mt6897/ISP_mapping.db \
    vendor/lenovo/tb373fu/proprietary/vendor/bin/crossbuild/DataSet/SQLiteModule/db/tuning_DB/imx766o_mipi_raw/mt6897/ISP_param.db:$(TARGET_COPY_OUT_VENDOR)/bin/crossbuild/DataSet/SQLiteModule/db/tuning_DB/imx766o_mipi_raw/mt6897/ISP_param.db \
    vendor/lenovo/tb373fu/proprietary/vendor/bin/crossbuild/DataSet/SQLiteModule/db/tuning_DB/imx866_mipi_raw/mt6897/ISP_mapping.db:$(TARGET_COPY_OUT_VENDOR)/bin/crossbuild/DataSet/SQLiteModule/db/tuning_DB/imx866_mipi_raw/mt6897/ISP_mapping.db \
    vendor/lenovo/tb373fu/proprietary/vendor/bin/crossbuild/DataSet/SQLiteModule/db/tuning_DB/imx866_mipi_raw/mt6897/ISP_param.db:$(TARGET_COPY_OUT_VENDOR)/bin/crossbuild/DataSet/SQLiteModule/db/tuning_DB/imx866_mipi_raw/mt6897/ISP_param.db \
    vendor/lenovo/tb373fu/proprietary/vendor/bin/crossbuild/DataSet/SQLiteModule/db/tuning_DB/imx989_mipi_raw/mt6897/ISP_mapping.db:$(TARGET_COPY_OUT_VENDOR)/bin/crossbuild/DataSet/SQLiteModule/db/tuning_DB/imx989_mipi_raw/mt6897/ISP_mapping.db \
    vendor/lenovo/tb373fu/proprietary/vendor/bin/crossbuild/DataSet/SQLiteModule/db/tuning_DB/imx989_mipi_raw/mt6897/ISP_param.db:$(TARGET_COPY_OUT_VENDOR)/bin/crossbuild/DataSet/SQLiteModule/db/tuning_DB/imx989_mipi_raw/mt6897/ISP_param.db \
    vendor/lenovo/tb373fu/proprietary/vendor/bin/crossbuild/DataSet/SQLiteModule/db/tuning_DB/mt6897/ISP_info.db:$(TARGET_COPY_OUT_VENDOR)/bin/crossbuild/DataSet/SQLiteModule/db/tuning_DB/mt6897/ISP_info.db \
    vendor/lenovo/tb373fu/proprietary/vendor/bin/crossbuild/DataSet/SQLiteModule/db/tuning_DB/ov13b10_mipi_raw/mt6897/ISP_mapping.db:$(TARGET_COPY_OUT_VENDOR)/bin/crossbuild/DataSet/SQLiteModule/db/tuning_DB/ov13b10_mipi_raw/mt6897/ISP_mapping.db \
    vendor/lenovo/tb373fu/proprietary/vendor/bin/crossbuild/DataSet/SQLiteModule/db/tuning_DB/ov13b10_mipi_raw/mt6897/ISP_param.db:$(TARGET_COPY_OUT_VENDOR)/bin/crossbuild/DataSet/SQLiteModule/db/tuning_DB/ov13b10_mipi_raw/mt6897/ISP_param.db \
    vendor/lenovo/tb373fu/proprietary/vendor/bin/crossbuild/DataSet/SQLiteModule/db/tuning_DB/ov48b_mipi_raw/mt6897/ISP_mapping.db:$(TARGET_COPY_OUT_VENDOR)/bin/crossbuild/DataSet/SQLiteModule/db/tuning_DB/ov48b_mipi_raw/mt6897/ISP_mapping.db \
    vendor/lenovo/tb373fu/proprietary/vendor/bin/crossbuild/DataSet/SQLiteModule/db/tuning_DB/ov48b_mipi_raw/mt6897/ISP_param.db:$(TARGET_COPY_OUT_VENDOR)/bin/crossbuild/DataSet/SQLiteModule/db/tuning_DB/ov48b_mipi_raw/mt6897/ISP_param.db \
    vendor/lenovo/tb373fu/proprietary/vendor/bin/crossbuild/DataSet/SQLiteModule/db/tuning_DB/s5k3m5sx_mipi_raw/mt6897/ISP_mapping.db:$(TARGET_COPY_OUT_VENDOR)/bin/crossbuild/DataSet/SQLiteModule/db/tuning_DB/s5k3m5sx_mipi_raw/mt6897/ISP_mapping.db \
    vendor/lenovo/tb373fu/proprietary/vendor/bin/crossbuild/DataSet/SQLiteModule/db/tuning_DB/s5k3m5sx_mipi_raw/mt6897/ISP_param.db:$(TARGET_COPY_OUT_VENDOR)/bin/crossbuild/DataSet/SQLiteModule/db/tuning_DB/s5k3m5sx_mipi_raw/mt6897/ISP_param.db \
    vendor/lenovo/tb373fu/proprietary/vendor/bin/crossbuild/DataSet/SQLiteModule/db/tuning_DB/s5k3m5sxo_mipi_raw/mt6897/ISP_mapping.db:$(TARGET_COPY_OUT_VENDOR)/bin/crossbuild/DataSet/SQLiteModule/db/tuning_DB/s5k3m5sxo_mipi_raw/mt6897/ISP_mapping.db \
    vendor/lenovo/tb373fu/proprietary/vendor/bin/crossbuild/DataSet/SQLiteModule/db/tuning_DB/s5k3m5sxo_mipi_raw/mt6897/ISP_param.db:$(TARGET_COPY_OUT_VENDOR)/bin/crossbuild/DataSet/SQLiteModule/db/tuning_DB/s5k3m5sxo_mipi_raw/mt6897/ISP_param.db \
    vendor/lenovo/tb373fu/proprietary/vendor/bin/crossbuild/DataSet/SQLiteModule/db/tuning_DB/s5k3p9sp_mipi_raw/mt6897/ISP_mapping.db:$(TARGET_COPY_OUT_VENDOR)/bin/crossbuild/DataSet/SQLiteModule/db/tuning_DB/s5k3p9sp_mipi_raw/mt6897/ISP_mapping.db \
    vendor/lenovo/tb373fu/proprietary/vendor/bin/crossbuild/DataSet/SQLiteModule/db/tuning_DB/s5k3p9sp_mipi_raw/mt6897/ISP_param.db:$(TARGET_COPY_OUT_VENDOR)/bin/crossbuild/DataSet/SQLiteModule/db/tuning_DB/s5k3p9sp_mipi_raw/mt6897/ISP_param.db \
    vendor/lenovo/tb373fu/proprietary/vendor/bin/crossbuild/DataSet/SQLiteModule/db/tuning_DB/s5k4h7_mipi_raw/mt6897/ISP_mapping.db:$(TARGET_COPY_OUT_VENDOR)/bin/crossbuild/DataSet/SQLiteModule/db/tuning_DB/s5k4h7_mipi_raw/mt6897/ISP_mapping.db \
    vendor/lenovo/tb373fu/proprietary/vendor/bin/crossbuild/DataSet/SQLiteModule/db/tuning_DB/s5k4h7_mipi_raw/mt6897/ISP_param.db:$(TARGET_COPY_OUT_VENDOR)/bin/crossbuild/DataSet/SQLiteModule/db/tuning_DB/s5k4h7_mipi_raw/mt6897/ISP_param.db \
    vendor/lenovo/tb373fu/proprietary/vendor/bin/crossbuild/DataSet/SQLiteModule/db/tuning_DB/sc820cs_mipi_raw/mt6897/ISP_mapping.db:$(TARGET_COPY_OUT_VENDOR)/bin/crossbuild/DataSet/SQLiteModule/db/tuning_DB/sc820cs_mipi_raw/mt6897/ISP_mapping.db \
    vendor/lenovo/tb373fu/proprietary/vendor/bin/crossbuild/DataSet/SQLiteModule/db/tuning_DB/sc820cs_mipi_raw/mt6897/ISP_param.db:$(TARGET_COPY_OUT_VENDOR)/bin/crossbuild/DataSet/SQLiteModule/db/tuning_DB/sc820cs_mipi_raw/mt6897/ISP_param.db \
    vendor/lenovo/tb373fu/proprietary/vendor/bin/crossbuild/DataSet/SQLiteModule/db/tuning_DB_aov/default_sensor/mt6897/ISP_mapping.db:$(TARGET_COPY_OUT_VENDOR)/bin/crossbuild/DataSet/SQLiteModule/db/tuning_DB_aov/default_sensor/mt6897/ISP_mapping.db \
    vendor/lenovo/tb373fu/proprietary/vendor/bin/crossbuild/DataSet/SQLiteModule/db/tuning_DB_aov/default_sensor/mt6897/ISP_param.db:$(TARGET_COPY_OUT_VENDOR)/bin/crossbuild/DataSet/SQLiteModule/db/tuning_DB_aov/default_sensor/mt6897/ISP_param.db \
    vendor/lenovo/tb373fu/proprietary/vendor/bin/crossbuild/DataSet/SQLiteModule/db/tuning_DB_aov/mt6897/ISP_info.db:$(TARGET_COPY_OUT_VENDOR)/bin/crossbuild/DataSet/SQLiteModule/db/tuning_DB_aov/mt6897/ISP_info.db \
    vendor/lenovo/tb373fu/proprietary/vendor/etc/audio_device.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_device.xml \
    vendor/lenovo/tb373fu/proprietary/vendor/etc/audio_param/AudioParamOptions_mgvi.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/AudioParamOptions_mgvi.xml \
    vendor/lenovo/tb373fu/proprietary/vendor/etc/audio_param/AudioParamOptions_vext.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/AudioParamOptions_vext.xml \
    vendor/lenovo/tb373fu/proprietary/vendor/etc/audio_param/BtInfo_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/BtInfo_AudioParam.xml \
    vendor/lenovo/tb373fu/proprietary/vendor/etc/audio_param/BtInfo_ParamUnitDesc.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/BtInfo_ParamUnitDesc.xml \
    vendor/lenovo/tb373fu/proprietary/vendor/etc/audio_param/CRSVolUI_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/CRSVolUI_AudioParam.xml \
    vendor/lenovo/tb373fu/proprietary/vendor/etc/audio_param/CRSVolUI_ParamUnitDesc.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/CRSVolUI_ParamUnitDesc.xml \
    vendor/lenovo/tb373fu/proprietary/vendor/etc/audio_param/CRSVol_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/CRSVol_AudioParam.xml \
    vendor/lenovo/tb373fu/proprietary/vendor/etc/audio_param/CRSVol_ParamUnitDesc.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/CRSVol_ParamUnitDesc.xml \
    vendor/lenovo/tb373fu/proprietary/vendor/etc/audio_param/HpImpedance_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/HpImpedance_AudioParam.xml \
    vendor/lenovo/tb373fu/proprietary/vendor/etc/audio_param/HpImpedance_ParamUnitDesc.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/HpImpedance_ParamUnitDesc.xml \
    vendor/lenovo/tb373fu/proprietary/vendor/etc/audio_param/MicInfo_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/MicInfo_AudioParam.xml \
    vendor/lenovo/tb373fu/proprietary/vendor/etc/audio_param/MicInfo_ParamUnitDesc.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/MicInfo_ParamUnitDesc.xml \
    vendor/lenovo/tb373fu/proprietary/vendor/etc/audio_param/PlaybackACF_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/PlaybackACF_AudioParam.xml \
    vendor/lenovo/tb373fu/proprietary/vendor/etc/audio_param/PlaybackACF_ParamUnitDesc.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/PlaybackACF_ParamUnitDesc.xml \
    vendor/lenovo/tb373fu/proprietary/vendor/etc/audio_param/PlaybackDRC_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/PlaybackDRC_AudioParam.xml \
    vendor/lenovo/tb373fu/proprietary/vendor/etc/audio_param/PlaybackDRC_ParamUnitDesc.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/PlaybackDRC_ParamUnitDesc.xml \
    vendor/lenovo/tb373fu/proprietary/vendor/etc/audio_param/PlaybackHCF_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/PlaybackHCF_AudioParam.xml \
    vendor/lenovo/tb373fu/proprietary/vendor/etc/audio_param/PlaybackHCF_ParamUnitDesc.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/PlaybackHCF_ParamUnitDesc.xml \
    vendor/lenovo/tb373fu/proprietary/vendor/etc/audio_param/PlaybackVolAna_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/PlaybackVolAna_AudioParam.xml \
    vendor/lenovo/tb373fu/proprietary/vendor/etc/audio_param/PlaybackVolAna_ParamUnitDesc.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/PlaybackVolAna_ParamUnitDesc.xml \
    vendor/lenovo/tb373fu/proprietary/vendor/etc/audio_param/PlaybackVolDigi_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/PlaybackVolDigi_AudioParam.xml \
    vendor/lenovo/tb373fu/proprietary/vendor/etc/audio_param/PlaybackVolDigi_ParamUnitDesc.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/PlaybackVolDigi_ParamUnitDesc.xml \
    vendor/lenovo/tb373fu/proprietary/vendor/etc/audio_param/PlaybackVolUI_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/PlaybackVolUI_AudioParam.xml \
    vendor/lenovo/tb373fu/proprietary/vendor/etc/audio_param/PlaybackVolUI_ParamUnitDesc.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/PlaybackVolUI_ParamUnitDesc.xml \
    vendor/lenovo/tb373fu/proprietary/vendor/etc/audio_param/Playback_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/Playback_AudioParam.xml \
    vendor/lenovo/tb373fu/proprietary/vendor/etc/audio_param/Playback_ParamTreeView.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/Playback_ParamTreeView.xml \
    vendor/lenovo/tb373fu/proprietary/vendor/etc/audio_param/Playback_ParamUnitDesc.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/Playback_ParamUnitDesc.xml \
    vendor/lenovo/tb373fu/proprietary/vendor/etc/audio_param/RecordDMNR_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/RecordDMNR_AudioParam.xml \
    vendor/lenovo/tb373fu/proprietary/vendor/etc/audio_param/RecordDMNR_ParamUnitDesc.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/RecordDMNR_ParamUnitDesc.xml \
    vendor/lenovo/tb373fu/proprietary/vendor/etc/audio_param/RecordFIR_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/RecordFIR_AudioParam.xml \
    vendor/lenovo/tb373fu/proprietary/vendor/etc/audio_param/RecordFIR_ParamUnitDesc.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/RecordFIR_ParamUnitDesc.xml \
    vendor/lenovo/tb373fu/proprietary/vendor/etc/audio_param/RecordUI_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/RecordUI_AudioParam.xml \
    vendor/lenovo/tb373fu/proprietary/vendor/etc/audio_param/RecordUI_ParamUnitDesc.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/RecordUI_ParamUnitDesc.xml \
    vendor/lenovo/tb373fu/proprietary/vendor/etc/audio_param/RecordVolUI_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/RecordVolUI_AudioParam.xml \
    vendor/lenovo/tb373fu/proprietary/vendor/etc/audio_param/RecordVolUI_ParamUnitDesc.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/RecordVolUI_ParamUnitDesc.xml \
    vendor/lenovo/tb373fu/proprietary/vendor/etc/audio_param/RecordVol_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/RecordVol_AudioParam.xml \
    vendor/lenovo/tb373fu/proprietary/vendor/etc/audio_param/RecordVol_ParamUnitDesc.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/RecordVol_ParamUnitDesc.xml \
    vendor/lenovo/tb373fu/proprietary/vendor/etc/audio_param/Record_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/Record_AudioParam.xml \
    vendor/lenovo/tb373fu/proprietary/vendor/etc/audio_param/Record_ParamTreeView.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/Record_ParamTreeView.xml \
    vendor/lenovo/tb373fu/proprietary/vendor/etc/audio_param/Record_ParamUnitDesc.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/Record_ParamUnitDesc.xml \
    vendor/lenovo/tb373fu/proprietary/vendor/etc/audio_param/RingbackVolUI_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/RingbackVolUI_AudioParam.xml \
    vendor/lenovo/tb373fu/proprietary/vendor/etc/audio_param/RingbackVolUI_ParamUnitDesc.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/RingbackVolUI_ParamUnitDesc.xml \
    vendor/lenovo/tb373fu/proprietary/vendor/etc/audio_param/RingbackVol_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/RingbackVol_AudioParam.xml \
    vendor/lenovo/tb373fu/proprietary/vendor/etc/audio_param/RingbackVol_ParamUnitDesc.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/RingbackVol_ParamUnitDesc.xml \
    vendor/lenovo/tb373fu/proprietary/vendor/etc/audio_param/SmartPa_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/SmartPa_AudioParam.xml \
    vendor/lenovo/tb373fu/proprietary/vendor/etc/audio_param/SmartPa_ParamUnitDesc.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/SmartPa_ParamUnitDesc.xml \
    vendor/lenovo/tb373fu/proprietary/vendor/etc/audio_param/SoundEnhancement_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/SoundEnhancement_AudioParam.xml \
    vendor/lenovo/tb373fu/proprietary/vendor/etc/audio_param/SoundEnhancement_ParamUnitDesc.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/SoundEnhancement_ParamUnitDesc.xml \
    vendor/lenovo/tb373fu/proprietary/vendor/etc/audio_param/SpeechAcousticShock_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/SpeechAcousticShock_AudioParam.xml \
    vendor/lenovo/tb373fu/proprietary/vendor/etc/audio_param/SpeechAcousticShock_ParamUnitDesc.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/SpeechAcousticShock_ParamUnitDesc.xml \
    vendor/lenovo/tb373fu/proprietary/vendor/etc/audio_param/SpeechDMNR_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/SpeechDMNR_AudioParam.xml \
    vendor/lenovo/tb373fu/proprietary/vendor/etc/audio_param/SpeechDMNR_ParamUnitDesc.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/SpeechDMNR_ParamUnitDesc.xml \
    vendor/lenovo/tb373fu/proprietary/vendor/etc/audio_param/SpeechEchoRef_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/SpeechEchoRef_AudioParam.xml \
    vendor/lenovo/tb373fu/proprietary/vendor/etc/audio_param/SpeechEchoRef_ParamUnitDesc.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/SpeechEchoRef_ParamUnitDesc.xml \
    vendor/lenovo/tb373fu/proprietary/vendor/etc/audio_param/SpeechGeneral_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/SpeechGeneral_AudioParam.xml \
    vendor/lenovo/tb373fu/proprietary/vendor/etc/audio_param/SpeechGeneral_ParamUnitDesc.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/SpeechGeneral_ParamUnitDesc.xml \
    vendor/lenovo/tb373fu/proprietary/vendor/etc/audio_param/SpeechMagiClarity_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/SpeechMagiClarity_AudioParam.xml \
    vendor/lenovo/tb373fu/proprietary/vendor/etc/audio_param/SpeechMagiClarity_ParamUnitDesc.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/SpeechMagiClarity_ParamUnitDesc.xml \
    vendor/lenovo/tb373fu/proprietary/vendor/etc/audio_param/SpeechNetwork_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/SpeechNetwork_AudioParam.xml \
    vendor/lenovo/tb373fu/proprietary/vendor/etc/audio_param/SpeechNetwork_ParamUnitDesc.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/SpeechNetwork_ParamUnitDesc.xml \
    vendor/lenovo/tb373fu/proprietary/vendor/etc/audio_param/SpeechUI_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/SpeechUI_AudioParam.xml \
    vendor/lenovo/tb373fu/proprietary/vendor/etc/audio_param/SpeechUI_ParamUnitDesc.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/SpeechUI_ParamUnitDesc.xml \
    vendor/lenovo/tb373fu/proprietary/vendor/etc/audio_param/SpeechVolUI_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/SpeechVolUI_AudioParam.xml \
    vendor/lenovo/tb373fu/proprietary/vendor/etc/audio_param/SpeechVolUI_ParamUnitDesc.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/SpeechVolUI_ParamUnitDesc.xml \
    vendor/lenovo/tb373fu/proprietary/vendor/etc/audio_param/SpeechVol_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/SpeechVol_AudioParam.xml \
    vendor/lenovo/tb373fu/proprietary/vendor/etc/audio_param/SpeechVol_ParamUnitDesc.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/SpeechVol_ParamUnitDesc.xml \
    vendor/lenovo/tb373fu/proprietary/vendor/etc/audio_param/Speech_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/Speech_AudioParam.xml \
    vendor/lenovo/tb373fu/proprietary/vendor/etc/audio_param/Speech_ParamTreeView.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/Speech_ParamTreeView.xml \
    vendor/lenovo/tb373fu/proprietary/vendor/etc/audio_param/Speech_ParamUnitDesc.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/Speech_ParamUnitDesc.xml \
    vendor/lenovo/tb373fu/proprietary/vendor/etc/audio_param/USBCall_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/USBCall_AudioParam.xml \
    vendor/lenovo/tb373fu/proprietary/vendor/etc/audio_param/USBCall_ParamUnitDesc.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/USBCall_ParamUnitDesc.xml \
    vendor/lenovo/tb373fu/proprietary/vendor/etc/audio_param/USBDevice_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/USBDevice_AudioParam.xml \
    vendor/lenovo/tb373fu/proprietary/vendor/etc/audio_param/USBDevice_ParamUnitDesc.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/USBDevice_ParamUnitDesc.xml \
    vendor/lenovo/tb373fu/proprietary/vendor/etc/audio_param/Ultrasound_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/Ultrasound_AudioParam.xml \
    vendor/lenovo/tb373fu/proprietary/vendor/etc/audio_param/Ultrasound_ParamUnitDesc.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/Ultrasound_ParamUnitDesc.xml \
    vendor/lenovo/tb373fu/proprietary/vendor/etc/audio_param/UplinkConfiguration_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/UplinkConfiguration_AudioParam.xml \
    vendor/lenovo/tb373fu/proprietary/vendor/etc/audio_param/UplinkConfiguration_ParamUnitDesc.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/UplinkConfiguration_ParamUnitDesc.xml \
    vendor/lenovo/tb373fu/proprietary/vendor/etc/audio_param/VoIPDMNR_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/VoIPDMNR_AudioParam.xml \
    vendor/lenovo/tb373fu/proprietary/vendor/etc/audio_param/VoIPDMNR_ParamUnitDesc.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/VoIPDMNR_ParamUnitDesc.xml \
    vendor/lenovo/tb373fu/proprietary/vendor/etc/audio_param/VoIPGeneral_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/VoIPGeneral_AudioParam.xml \
    vendor/lenovo/tb373fu/proprietary/vendor/etc/audio_param/VoIPGeneral_ParamUnitDesc.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/VoIPGeneral_ParamUnitDesc.xml \
    vendor/lenovo/tb373fu/proprietary/vendor/etc/audio_param/VoIPUI_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/VoIPUI_AudioParam.xml \
    vendor/lenovo/tb373fu/proprietary/vendor/etc/audio_param/VoIPUI_ParamUnitDesc.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/VoIPUI_ParamUnitDesc.xml \
    vendor/lenovo/tb373fu/proprietary/vendor/etc/audio_param/VoIPVolUI_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/VoIPVolUI_AudioParam.xml \
    vendor/lenovo/tb373fu/proprietary/vendor/etc/audio_param/VoIPVolUI_ParamUnitDesc.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/VoIPVolUI_ParamUnitDesc.xml \
    vendor/lenovo/tb373fu/proprietary/vendor/etc/audio_param/VoIPVol_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/VoIPVol_AudioParam.xml \
    vendor/lenovo/tb373fu/proprietary/vendor/etc/audio_param/VoIPVol_ParamUnitDesc.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/VoIPVol_ParamUnitDesc.xml \
    vendor/lenovo/tb373fu/proprietary/vendor/etc/audio_param/VoIP_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/VoIP_AudioParam.xml \
    vendor/lenovo/tb373fu/proprietary/vendor/etc/audio_param/VoIP_ParamTreeView.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/VoIP_ParamTreeView.xml \
    vendor/lenovo/tb373fu/proprietary/vendor/etc/audio_param/VoIP_ParamUnitDesc.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/VoIP_ParamUnitDesc.xml \
    vendor/lenovo/tb373fu/proprietary/vendor/etc/audio_param/VoIPv2DMNR_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/VoIPv2DMNR_AudioParam.xml \
    vendor/lenovo/tb373fu/proprietary/vendor/etc/audio_param/VoIPv2DMNR_ParamUnitDesc.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/VoIPv2DMNR_ParamUnitDesc.xml \
    vendor/lenovo/tb373fu/proprietary/vendor/etc/audio_param/VoIPv2General_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/VoIPv2General_AudioParam.xml \
    vendor/lenovo/tb373fu/proprietary/vendor/etc/audio_param/VoIPv2General_ParamUnitDesc.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/VoIPv2General_ParamUnitDesc.xml \
    vendor/lenovo/tb373fu/proprietary/vendor/etc/audio_param/VoIPv2UI_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/VoIPv2UI_AudioParam.xml \
    vendor/lenovo/tb373fu/proprietary/vendor/etc/audio_param/VoIPv2UI_ParamUnitDesc.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/VoIPv2UI_ParamUnitDesc.xml \
    vendor/lenovo/tb373fu/proprietary/vendor/etc/audio_param/VoIPv2_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/VoIPv2_AudioParam.xml \
    vendor/lenovo/tb373fu/proprietary/vendor/etc/audio_param/VoIPv2_ParamTreeView.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/VoIPv2_ParamTreeView.xml \
    vendor/lenovo/tb373fu/proprietary/vendor/etc/audio_param/VoIPv2_ParamUnitDesc.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/VoIPv2_ParamUnitDesc.xml \
    vendor/lenovo/tb373fu/proprietary/vendor/etc/audio_param/VoWCommonSetting_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/VoWCommonSetting_AudioParam.xml \
    vendor/lenovo/tb373fu/proprietary/vendor/etc/audio_param/VoWCommonSetting_ParamUnitDesc.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/VoWCommonSetting_ParamUnitDesc.xml \
    vendor/lenovo/tb373fu/proprietary/vendor/etc/audio_param/VoWCompatibilityCode_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/VoWCompatibilityCode_AudioParam.xml \
    vendor/lenovo/tb373fu/proprietary/vendor/etc/audio_param/VoWCompatibilityCode_ParamUnitDesc.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/VoWCompatibilityCode_ParamUnitDesc.xml \
    vendor/lenovo/tb373fu/proprietary/vendor/etc/audio_param/VoWDspAec_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/VoWDspAec_AudioParam.xml \
    vendor/lenovo/tb373fu/proprietary/vendor/etc/audio_param/VoWDspAec_ParamUnitDesc.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/VoWDspAec_ParamUnitDesc.xml \
    vendor/lenovo/tb373fu/proprietary/vendor/etc/audio_param/VoWEngineFeature_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/VoWEngineFeature_AudioParam.xml \
    vendor/lenovo/tb373fu/proprietary/vendor/etc/audio_param/VoWEngineFeature_ParamUnitDesc.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/VoWEngineFeature_ParamUnitDesc.xml \
    vendor/lenovo/tb373fu/proprietary/vendor/etc/audio_param/VoWHwVad_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/VoWHwVad_AudioParam.xml \
    vendor/lenovo/tb373fu/proprietary/vendor/etc/audio_param/VoWHwVad_ParamUnitDesc.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/VoWHwVad_ParamUnitDesc.xml \
    vendor/lenovo/tb373fu/proprietary/vendor/etc/audio_param/VoWMicSetting_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/VoWMicSetting_AudioParam.xml \
    vendor/lenovo/tb373fu/proprietary/vendor/etc/audio_param/VoWMicSetting_ParamUnitDesc.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/VoWMicSetting_ParamUnitDesc.xml \
    vendor/lenovo/tb373fu/proprietary/vendor/etc/audio_param/VoWVoiceCommand_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/VoWVoiceCommand_AudioParam.xml \
    vendor/lenovo/tb373fu/proprietary/vendor/etc/audio_param/VoWVoiceCommand_ParamUnitDesc.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/VoWVoiceCommand_ParamUnitDesc.xml \
    vendor/lenovo/tb373fu/proprietary/vendor/etc/audio_param/VolumeGainMapUL_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/VolumeGainMapUL_AudioParam.xml \
    vendor/lenovo/tb373fu/proprietary/vendor/etc/audio_param/VolumeGainMapUL_ParamUnitDesc.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/VolumeGainMapUL_ParamUnitDesc.xml \
    vendor/lenovo/tb373fu/proprietary/vendor/etc/audio_param/VolumeGainMap_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/VolumeGainMap_AudioParam.xml \
    vendor/lenovo/tb373fu/proprietary/vendor/etc/audio_param/VolumeGainMap_ParamUnitDesc.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/VolumeGainMap_ParamUnitDesc.xml \
    vendor/lenovo/tb373fu/proprietary/vendor/etc/audio_param/Volume_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/Volume_AudioParam.xml \
    vendor/lenovo/tb373fu/proprietary/vendor/etc/audio_param/Volume_ParamUnitDesc.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/Volume_ParamUnitDesc.xml \
    vendor/lenovo/tb373fu/proprietary/vendor/etc/aurisys_config.xml:$(TARGET_COPY_OUT_VENDOR)/etc/aurisys_config.xml \
    vendor/lenovo/tb373fu/proprietary/vendor/etc/aurisys_config_hifi3.xml:$(TARGET_COPY_OUT_VENDOR)/etc/aurisys_config_hifi3.xml \
    vendor/lenovo/tb373fu/proprietary/vendor/etc/aurisys_config_rv.xml:$(TARGET_COPY_OUT_VENDOR)/etc/aurisys_config_rv.xml \
    vendor/lenovo/tb373fu/proprietary/vendor/etc/cust_color.xml:$(TARGET_COPY_OUT_VENDOR)/etc/cust_color.xml \
    vendor/lenovo/tb373fu/proprietary/vendor/etc/gralloc/cam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/gralloc/cam.xml \
    vendor/lenovo/tb373fu/proprietary/vendor/etc/gralloc/dpu.xml:$(TARGET_COPY_OUT_VENDOR)/etc/gralloc/dpu.xml \
    vendor/lenovo/tb373fu/proprietary/vendor/etc/gralloc/dpu_aeu.xml:$(TARGET_COPY_OUT_VENDOR)/etc/gralloc/dpu_aeu.xml \
    vendor/lenovo/tb373fu/proprietary/vendor/etc/gralloc/gpu.xml:$(TARGET_COPY_OUT_VENDOR)/etc/gralloc/gpu.xml \
    vendor/lenovo/tb373fu/proprietary/vendor/etc/gralloc/vpu.xml:$(TARGET_COPY_OUT_VENDOR)/etc/gralloc/vpu.xml \
    vendor/lenovo/tb373fu/proprietary/vendor/etc/init.insmod.mt6897.cfg:$(TARGET_COPY_OUT_VENDOR)/etc/init.insmod.mt6897.cfg \
    vendor/lenovo/tb373fu/proprietary/vendor/etc/init/android.hardware.gatekeeper-service.beanpod.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/android.hardware.gatekeeper-service.beanpod.rc \
    vendor/lenovo/tb373fu/proprietary/vendor/etc/init/android.hardware.graphics.allocator-V2-service-mediatek.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/android.hardware.graphics.allocator-V2-service-mediatek.rc \
    vendor/lenovo/tb373fu/proprietary/vendor/etc/init/android.hardware.graphics.composer@3.2-service.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/android.hardware.graphics.composer@3.2-service.rc \
    vendor/lenovo/tb373fu/proprietary/vendor/etc/init/android.hardware.media.c2@1.2-mediatek-64b.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/android.hardware.media.c2@1.2-mediatek-64b.rc \
    vendor/lenovo/tb373fu/proprietary/vendor/etc/init/android.hardware.neuralnetworks-shim-service-mtk.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/android.hardware.neuralnetworks-shim-service-mtk.rc \
    vendor/lenovo/tb373fu/proprietary/vendor/etc/init/android.hardware.security.keymint-service.beanpod.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/android.hardware.security.keymint-service.beanpod.rc \
    vendor/lenovo/tb373fu/proprietary/vendor/etc/init/camerahalserver.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/camerahalserver.rc \
    vendor/lenovo/tb373fu/proprietary/vendor/etc/init/chipinfo_init.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/chipinfo_init.rc \
    vendor/lenovo/tb373fu/proprietary/vendor/etc/init/fuelgauged_init.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/fuelgauged_init.rc \
    vendor/lenovo/tb373fu/proprietary/vendor/etc/init/fuelgauged_nvram_init.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/fuelgauged_nvram_init.rc \
    vendor/lenovo/tb373fu/proprietary/vendor/etc/init/hw/init.mtkgki.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/hw/init.mtkgki.rc \
    vendor/lenovo/tb373fu/proprietary/vendor/etc/init/init.bt_drv.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/init.bt_drv.rc \
    vendor/lenovo/tb373fu/proprietary/vendor/etc/init/init.wlan_drv.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/init.wlan_drv.rc \
    vendor/lenovo/tb373fu/proprietary/vendor/etc/init/microtrust.bp_kmsetkey_ca.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/microtrust.bp_kmsetkey_ca.rc \
    vendor/lenovo/tb373fu/proprietary/vendor/etc/init/microtrust.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/microtrust.rc \
    vendor/lenovo/tb373fu/proprietary/vendor/etc/init/nvram_daemon.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/nvram_daemon.rc \
    vendor/lenovo/tb373fu/proprietary/vendor/etc/init/vendor.mediatek.hardware.mmagent-service.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/vendor.mediatek.hardware.mmagent-service.rc \
    vendor/lenovo/tb373fu/proprietary/vendor/etc/init/vendor.mediatek.hardware.mmlpq@V1-service.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/vendor.mediatek.hardware.mmlpq@V1-service.rc \
    vendor/lenovo/tb373fu/proprietary/vendor/etc/init/vendor.mediatek.hardware.nvram-sevice.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/vendor.mediatek.hardware.nvram-sevice.rc \
    vendor/lenovo/tb373fu/proprietary/vendor/etc/init/vendor.mediatek.hardware.pq_aidl-service.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/vendor.mediatek.hardware.pq_aidl-service.rc \
    vendor/lenovo/tb373fu/proprietary/vendor/etc/init/wlan_assistant.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/wlan_assistant.rc \
    vendor/lenovo/tb373fu/proprietary/vendor/etc/mali_platform.config:$(TARGET_COPY_OUT_VENDOR)/etc/mali_platform.config \
    vendor/lenovo/tb373fu/proprietary/vendor/etc/nn/ot/neuron_detection.mdla5_0:$(TARGET_COPY_OUT_VENDOR)/etc/nn/ot/neuron_detection.mdla5_0 \
    vendor/lenovo/tb373fu/proprietary/vendor/etc/nn/ot/neuron_tracking.mdla5_0:$(TARGET_COPY_OUT_VENDOR)/etc/nn/ot/neuron_tracking.mdla5_0 \
    vendor/lenovo/tb373fu/proprietary/vendor/etc/nnapi_powerhal.json:$(TARGET_COPY_OUT_VENDOR)/etc/nnapi_powerhal.json \
    vendor/lenovo/tb373fu/proprietary/vendor/etc/panel-boe-nt36532-dsi-vdo_pq.xml:$(TARGET_COPY_OUT_VENDOR)/etc/panel-boe-nt36532-dsi-vdo_pq.xml \
    vendor/lenovo/tb373fu/proprietary/vendor/etc/panel-tianma-nt36532-dsi-vdo_pq.xml:$(TARGET_COPY_OUT_VENDOR)/etc/panel-tianma-nt36532-dsi-vdo_pq.xml \
    vendor/lenovo/tb373fu/proprietary/vendor/etc/panel-tianma-paper-nt36532-dsi-vdo_pq.xml:$(TARGET_COPY_OUT_VENDOR)/etc/panel-tianma-paper-nt36532-dsi-vdo_pq.xml \
    vendor/lenovo/tb373fu/proprietary/vendor/etc/pq_flag.xml:$(TARGET_COPY_OUT_VENDOR)/etc/pq_flag.xml \
    vendor/lenovo/tb373fu/proprietary/vendor/etc/public.libraries.txt:$(TARGET_COPY_OUT_VENDOR)/etc/public.libraries.txt \
    vendor/lenovo/tb373fu/proprietary/vendor/etc/seccomp_policy/android.hardware.media.c2@1.2-extended-seccomp-policy:$(TARGET_COPY_OUT_VENDOR)/etc/seccomp_policy/android.hardware.media.c2@1.2-extended-seccomp-policy \
    vendor/lenovo/tb373fu/proprietary/vendor/etc/seccomp_policy/android.hardware.media.c2@1.2-mediatek-seccomp-policy:$(TARGET_COPY_OUT_VENDOR)/etc/seccomp_policy/android.hardware.media.c2@1.2-mediatek-seccomp-policy \
    vendor/lenovo/tb373fu/proprietary/vendor/etc/usb_audio_accessory_only_policy_configuration.xml:$(TARGET_COPY_OUT_VENDOR)/etc/usb_audio_accessory_only_policy_configuration.xml \
    vendor/lenovo/tb373fu/proprietary/vendor/etc/wifi/p2p_supplicant_overlay.conf:$(TARGET_COPY_OUT_VENDOR)/etc/wifi/p2p_supplicant_overlay.conf \
    vendor/lenovo/tb373fu/proprietary/vendor/etc/wifi/wpa_supplicant.conf:$(TARGET_COPY_OUT_VENDOR)/etc/wifi/wpa_supplicant.conf \
    vendor/lenovo/tb373fu/proprietary/vendor/etc/wifi/wpa_supplicant_overlay.conf:$(TARGET_COPY_OUT_VENDOR)/etc/wifi/wpa_supplicant_overlay.conf \
    vendor/lenovo/tb373fu/proprietary/vendor/firmware/BT_FW.cfg:$(TARGET_COPY_OUT_VENDOR)/firmware/BT_FW.cfg \
    vendor/lenovo/tb373fu/proprietary/vendor/firmware/aw883xx_acf_gyt.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/aw883xx_acf_gyt.bin \
    vendor/lenovo/tb373fu/proprietary/vendor/firmware/aw883xx_acf_yc.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/aw883xx_acf_yc.bin \
    vendor/lenovo/tb373fu/proprietary/vendor/firmware/awinic_params.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/awinic_params.bin \
    vendor/lenovo/tb373fu/proprietary/vendor/firmware/awinic_sinwave_params.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/awinic_sinwave_params.bin \
    vendor/lenovo/tb373fu/proprietary/vendor/firmware/connfem.cfg:$(TARGET_COPY_OUT_VENDOR)/firmware/connfem.cfg \
    vendor/lenovo/tb373fu/proprietary/vendor/firmware/conninfra.cfg:$(TARGET_COPY_OUT_VENDOR)/firmware/conninfra.cfg \
    vendor/lenovo/tb373fu/proprietary/vendor/firmware/fm_cust.cfg:$(TARGET_COPY_OUT_VENDOR)/firmware/fm_cust.cfg \
    vendor/lenovo/tb373fu/proprietary/vendor/firmware/lib3a.ccu:$(TARGET_COPY_OUT_VENDOR)/firmware/lib3a.ccu \
    vendor/lenovo/tb373fu/proprietary/vendor/firmware/lib3a.ccu_dummy:$(TARGET_COPY_OUT_VENDOR)/firmware/lib3a.ccu_dummy \
    vendor/lenovo/tb373fu/proprietary/vendor/firmware/mali_csffw.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/mali_csffw.bin \
    vendor/lenovo/tb373fu/proprietary/vendor/firmware/mt6635_fm_v1_coeff.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/mt6635_fm_v1_coeff.bin \
    vendor/lenovo/tb373fu/proprietary/vendor/firmware/mt6635_fm_v1_patch.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/mt6635_fm_v1_patch.bin \
    vendor/lenovo/tb373fu/proprietary/vendor/firmware/remoteproc_scp:$(TARGET_COPY_OUT_VENDOR)/firmware/remoteproc_scp \
    vendor/lenovo/tb373fu/proprietary/vendor/firmware/soc_fm_v1_coeff.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/soc_fm_v1_coeff.bin \
    vendor/lenovo/tb373fu/proprietary/vendor/firmware/soc_fm_v1_patch.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/soc_fm_v1_patch.bin \
    vendor/lenovo/tb373fu/proprietary/vendor/firmware/txpowerctrl.cfg:$(TARGET_COPY_OUT_VENDOR)/firmware/txpowerctrl.cfg \
    vendor/lenovo/tb373fu/proprietary/vendor/firmware/wifi.cfg:$(TARGET_COPY_OUT_VENDOR)/firmware/wifi.cfg \
    vendor/lenovo/tb373fu/proprietary/vendor/thh/ta/0102030405060708090a0b0c0d0e0f10.ta:$(TARGET_COPY_OUT_VENDOR)/thh/ta/0102030405060708090a0b0c0d0e0f10.ta \
    vendor/lenovo/tb373fu/proprietary/vendor/thh/ta/020f0000000000000000000000000000.ta:$(TARGET_COPY_OUT_VENDOR)/thh/ta/020f0000000000000000000000000000.ta \
    vendor/lenovo/tb373fu/proprietary/vendor/thh/ta/06090000000000000000000000000000.ta:$(TARGET_COPY_OUT_VENDOR)/thh/ta/06090000000000000000000000000000.ta \
    vendor/lenovo/tb373fu/proprietary/vendor/thh/ta/08010203000000000000000000000000.ta:$(TARGET_COPY_OUT_VENDOR)/thh/ta/08010203000000000000000000000000.ta \
    vendor/lenovo/tb373fu/proprietary/vendor/thh/ta/08110000000000000000000000000000.ta:$(TARGET_COPY_OUT_VENDOR)/thh/ta/08110000000000000000000000000000.ta \
    vendor/lenovo/tb373fu/proprietary/vendor/thh/ta/40188311faf343488db888ad39496f9a.ta:$(TARGET_COPY_OUT_VENDOR)/thh/ta/40188311faf343488db888ad39496f9a.ta \
    vendor/lenovo/tb373fu/proprietary/vendor/thh/ta/5020170115e016302017012521300000.ta:$(TARGET_COPY_OUT_VENDOR)/thh/ta/5020170115e016302017012521300000.ta \
    vendor/lenovo/tb373fu/proprietary/vendor/thh/ta/5f7a5b3b29b041bca249524a031a00e3.ta:$(TARGET_COPY_OUT_VENDOR)/thh/ta/5f7a5b3b29b041bca249524a031a00e3.ta \
    vendor/lenovo/tb373fu/proprietary/vendor/thh/ta/7778c03fc30c4dd0a319ea29643d4d4b.ta:$(TARGET_COPY_OUT_VENDOR)/thh/ta/7778c03fc30c4dd0a319ea29643d4d4b.ta \
    vendor/lenovo/tb373fu/proprietary/vendor/thh/ta/93feffccd8ca11e796c7c7a21acb4932.ta:$(TARGET_COPY_OUT_VENDOR)/thh/ta/93feffccd8ca11e796c7c7a21acb4932.ta \
    vendor/lenovo/tb373fu/proprietary/vendor/thh/ta/abcd270ea5c44c58bcd3384a2fa2539e.ta:$(TARGET_COPY_OUT_VENDOR)/thh/ta/abcd270ea5c44c58bcd3384a2fa2539e.ta \
    vendor/lenovo/tb373fu/proprietary/vendor/thh/ta/c09c9c5daa504b78b0e46eda61556c3a.ta:$(TARGET_COPY_OUT_VENDOR)/thh/ta/c09c9c5daa504b78b0e46eda61556c3a.ta \
    vendor/lenovo/tb373fu/proprietary/vendor/thh/ta/c1882f2d885e4e13a8c8e2622461b2fa.ta:$(TARGET_COPY_OUT_VENDOR)/thh/ta/c1882f2d885e4e13a8c8e2622461b2fa.ta \
    vendor/lenovo/tb373fu/proprietary/vendor/thh/ta/c2882f2d885e4e13a8c8e2622461b2ff.ta:$(TARGET_COPY_OUT_VENDOR)/thh/ta/c2882f2d885e4e13a8c8e2622461b2ff.ta \
    vendor/lenovo/tb373fu/proprietary/vendor/thh/ta/d78d338b1ac349e09f65f4efe179739d.ta:$(TARGET_COPY_OUT_VENDOR)/thh/ta/d78d338b1ac349e09f65f4efe179739d.ta \
    vendor/lenovo/tb373fu/proprietary/vendor/thh/ta/d91f322ad5a441d5955110eda3272fc0.ta:$(TARGET_COPY_OUT_VENDOR)/thh/ta/d91f322ad5a441d5955110eda3272fc0.ta \
    vendor/lenovo/tb373fu/proprietary/vendor/thh/ta/e97c270ea5c44c58bcd3384a2fa2539e.ta:$(TARGET_COPY_OUT_VENDOR)/thh/ta/e97c270ea5c44c58bcd3384a2fa2539e.ta \
    vendor/lenovo/tb373fu/proprietary/vendor/thh/ta/isee_model.json:$(TARGET_COPY_OUT_VENDOR)/thh/ta/isee_model.json

PRODUCT_PACKAGES += \
    APUWareApusysAidlServer \
    APUWareUtilsAidlServer \
    android.hardware.bluetooth.audio-V3-ndk-v34 \
    android.hardware.bluetooth.audio-impl-mediatek \
    libGLES_meow \
    libMEOW_data \
    libMEOW_qt \
    libMEOW_trace \
    libGLES_mali \
    android.hardware.audio@7.1-impl-mediatek \
    android.hardware.sensors@2.X-subhal-mediatek \
    android.hardware.soundtrigger3-impl \
    audio.bluetooth.default \
    audio.primary.mediatek \
    hwcomposer.mtk_common \
    id_attestation.beanpod \
    kmsetkey.beanpod \
    android.hardware.graphics.allocator-V2-mediatek \
    android.hardware.graphics.mapper@4.0-impl-mediatek \
    mapper.mediatek \
    vendor.mediatek.hardware.pq_aidl-impl \
    vulkan.mali \
    sensors.mediatek.V2.0 \
    sound_trigger.primary.default \
    vendor.mediatek.hardware.audio-impl \
    vendor.mediatek.hardware.camera.atms_aidl@1.0-impl \
    vendor.mediatek.hardware.camera.bgservice_aidl@1.0-impl \
    vendor.mediatek.hardware.camera.isphal_aidl@1.0-impl \
    vendor.mediatek.hardware.nvram-impl \
    lib3a.ae.pipe \
    lib3a.custom.shading.flow \
    libBasicModule \
    libJpgEncPipe \
    libMcClient \
    libMtkSpeechEnh \
    libOpenCL \
    libSQLiteModule_VER_ALL \
    libTEECommon \
    lib_iir \
    libaaa_aaautil \
    libaaa_afassist_V2 \
    libaaa_afassistctrl \
    libaaa_gma \
    libaal_cust \
    libaal_key \
    libaal_sec \
    libaedv \
    libaimemc \
    libalsautils-v34 \
    libapu_mdw \
    libapu_mdw_batch \
    libapusys \
    libarmnn \
    libarmnn_ndk.mtk.vndk \
    libaudio_param_parser-vnd \
    libaudiocompensationfilter_vendor \
    libaudiocompensationfilterc \
    libaudiocomponentengine_vendor \
    libaudiocomponentenginec \
    libaudiocustparam_vendor \
    libaudiodcrflt_vendor \
    libaudiofmtconv \
    libaudioloudc \
    libaudioprimarydevicehalifclient \
    libaudiosmartpamtk \
    libaudiotoolkit_vendor \
    libaurisysdemo \
    libbessound_hd_mtk_vendor \
    libblisrc32_vendor \
    libbluetooth_audio_session_aidl_mtk \
    libbluetooth_mtk \
    libbluetooth_mtk_pure \
    libbt-vendor \
    libbwc \
    libcam.hal3a.custom.ae.HDRStateEvaluator \
    libcam.zoomoverridemgr \
    libcamalgo.WarpMapResizer \
    libcamalgo.dngop \
    libcamalgo.fdft \
    libcamalgo.hdr10p \
    libcamalgo.platform \
    libcamalgo.sat \
    libcamalgo.utility \
    libcamalgo.vsdofUtil \
    libcamalgo.warp \
    libcmdl \
    libcmdl_ndk.mtk.vndk \
    libcodec2_fsr \
    libcodec2_hidl@1.0-v34 \
    libcodec2_hidl@1.1-v34 \
    libcodec2_hidl@1.2-v34 \
    libcodec2_hidl_plugin-v34 \
    libcodec2_mtk_c2store \
    libcodec2_mtk_vdec \
    libcodec2_mtk_venc \
    libcodec2_soft_common-v34 \
    libcodec2_vndk-v34 \
    libcodec2_vpp_fa_plugin \
    libcodec2_vpp_mi_plugin \
    libcodec2_vpp_qt_plugin \
    libcodec2_vpp_rs_plugin \
    libcomposer_ext \
    libconnfem \
    libcustom_nvram \
    libcvsd_mtk \
    libdre \
    libfeature.hdr10 \
    libfeaturepolicy \
    libfile_op \
    libformatter \
    libged \
    libgpud \
    libgralloc_extra \
    libgralloc_metadata \
    libgralloctypes_mtk \
    libgz_gp_client \
    libgz_uree \
    libhdrvideo \
    libheichal \
    libhfmanager \
    libhwm \
    libimagebuffer_wrapper \
    libimsg_log \
    libion_mtk \
    libion_ulit \
    libjpeg-alpha-oal_vendor \
    libjpeg-alpha_vendor \
    libjpegdecoder-v34 \
    libjpegencoder-v34 \
    libkmsetkey \
    libksensor \
    libladder \
    libmsbc_mtk \
    libmtkcam_custom.utils \
    libmtkcam_custom_feature \
    libmtkcam_fdWarpConvert \
    libmtkcam_fdsan \
    libmtkcam_fdsan_wrapper \
    libmtkcam_grallocutils_aidlv1helper \
    libmtkcam_hal_custom_state \
    libmtkcam_hal_custom_utils \
    libmtkcam_perfctrl_wrapper \
    libmtkisp_metadata_v2 \
    libmtkisp_metadata_v3 \
    libmtklimiter_vendor \
    libmtkshifter_vendor \
    libmtkspparser \
    libmvpu_cic_ci_compiler \
    libmvpu_cic_ci_compiler_25 \
    libmvpu_clc_14_cl_compiler_25 \
    libmvpu_clc_14_mvpu_debuginfo_25 \
    libmvpu_clc_14_mvpu_elf_25 \
    libmvpu_clc_14_mvpu_isa_25 \
    libmvpu_clc_14_mvpu_utility_25 \
    libmvpu_clc_cl_compiler \
    libmvpu_clc_mvpu_debuginfo \
    libmvpu_clc_mvpu_elf \
    libmvpu_clc_mvpu_utility \
    libmvpu_clc_vpu_isa \
    libmvpu_config \
    libmvpu_config_data \
    libmvpu_engine \
    libmvpu_engine_25 \
    libmvpu_engine_25_pub \
    libmvpu_engine_pub \
    libmvpu_pattern \
    libmvpu_pattern_25 \
    libmvpu_pattern_25_pub \
    libmvpu_pattern_pub \
    libmvpu_runtime \
    libmvpu_runtime_25 \
    libmvpu_runtime_25_pub \
    libmvpu_runtime_builtin \
    libmvpu_runtime_builtin_25 \
    libmvpu_runtime_pub \
    libmvpu_wrapper \
    libmvpuop25_mtk_cv \
    libmvpuop25_mtk_nn \
    libmvpuop_mtk_cv \
    libmvpuop_mtk_nn \
    libn3d_tuning \
    libnpagent \
    libnvram \
    libnvram_sec \
    libnxp_extamp_intf \
    liboemcrypto \
    libpqframework \
    libpqhdrmetaparser \
    libpqsharememory \
    libpqtuning \
    libpqxmlflagparser \
    libpqxmlparser \
    libremosaic_wrapper \
    librt_extamp_intf \
    libscltm \
    libsfplugin_ccodec_utils-v34 \
    libsilkybrightnesscore \
    libspeech_enh_lib \
    libspeechparser_vendor \
    libstagefright_bufferqueue_helper-v35 \
    libsysenv \
    libteei_daemon_vfs \
    libthha \
    libultrahdr-v34 \
    libvow_ap_test_aa \
    libvow_ap_test_dd \
    libvow_ap_test_ha \
    libvow_ap_test_hh \
    libvow_ap_test_nn \
    libvow_ap_test_trip_aa \
    libvow_ap_test_trip_dd \
    libvow_ap_test_trip_ha \
    libvow_ap_test_trip_hh \
    libvow_ap_test_trip_nn \
    libvow_comp_test \
    libvpu \
    libwifi-hal-mtk \
    arm.graphics-V4-ndk \
    arm.mali.platform-V2-ndk \
    gc13a0_mipi_raw_IdxMgr \
    gc13a0_mipi_raw_tuning \
    lib3a.ae \
    lib3a.ae.stat \
    lib3a.af.assist.models1d \
    lib3a.af.assist.models2d \
    lib3a.af.assist \
    lib3a.af.assist.utils \
    lib3a.af.core \
    lib3a.af \
    lib3a.aishutter \
    lib3a.alsflicker \
    lib3a.awb.core \
    lib3a.awbsync \
    lib3a.cculog \
    lib3a.custom.ae.flow \
    lib3a.custom.ae \
    lib3a.custom.af.flow \
    lib3a.custom.awb.flow \
    lib3a.custom.stt.flow \
    lib3a.flash \
    lib3a.flicker \
    lib3a.log \
    lib3a.sensors.color \
    lib3a.sensors.flicker \
    lib3a.stat \
    libAIODcore \
    libAIOTcore \
    libAITrackingAFMgr \
    libDBAccessor_ISP \
    libMtkMediaController \
    libMtkMediaController_SAL \
    libSonyIMX519PdafWrapper \
    lib_bsscore \
    libaaa_feature \
    libaaa_ltm \
    libaaa_ltmx \
    libaaa_tnc \
    libaaa_toneutil \
    libaal_cust_func \
    libaalservice \
    libacdk \
    libaiawb_fs \
    libaiawb_moon \
    libaiawb_moon_model \
    libaiawb_p1ggm \
    libaiawb_sun \
    libaibc_tuning \
    libaibc_tuning_p2 \
    libaibc_tuning_p3 \
    libaibc_tuning_p4 \
    libaidepth_tuning \
    libaiseg_cache \
    libaiseg_model \
    libaiseg_p1ggm \
    libaiseg_sun \
    libaiselector \
    libalgo.aosp.log \
    libapiwrapper \
    libapudcutils \
    libarm_egl_properties_sysprop \
    libarm_gralloc_properties_sysprop \
    libarm_mali_config_sysprops \
    libcam.3a_isp.utils \
    libcam.afmgr \
    libcam.chdr \
    libcam.feature_utils \
    libcam.fw_me_tcy \
    libcam.hal3a.3aProvider \
    libcam.hal3a.afassitmgr \
    libcam.hal3a.cctsvr.v4l2 \
    libcam.hal3a.ctrl \
    libcam.hal3a.custom \
    libcam.hal3a.guard \
    libcam.hal3a.ircutdrv \
    libcam.hal3a.lensdrv \
    libcam.hal3a.log \
    libcam.hal3a.lscMgrApi \
    libcam.hal3a.oisdrv \
    libcam.hal3a.ozoomdrv \
    libcam.hal3a.pdstatmgr \
    libcam.hal3a.policy \
    libcam.hal3a \
    libcam.hal3a.tofdrv \
    libcam.hal3a.utils \
    libcam.hal3a.v3.ae.v4l2 \
    libcam.hal3a.v3.ai3a_v4l2 \
    libcam.hal3a.v3.awb_v4l2 \
    libcam.hal3a.v3.dng \
    libcam.hal3a.v3.flash.v4l2 \
    libcam.hal3a.v3.flicker.v4l2 \
    libcam.hal3a.v3.ir.v4l2 \
    libcam.hal3a.v3.lsctbl.v4l2 \
    libcam.hal3a.v3.nvram.v4l2 \
    libcam.hal3a.v3.sensor.v4l2 \
    libcam.hal3a.v3.strobe \
    libcam.hal3a.v3.stt_v4l2 \
    libcam.hal3a.v3.tone.mgr.v4l2 \
    libcam.halisp.SwTopCtrlMgr \
    libcam.halisp.TopCtrlMgr \
    libcam.halisp.TuningDataProvider \
    libcam.halisp.TuningDataProviderFactory \
    libcam.halisp.imp.v4l2 \
    libcam.halisp.plugin \
    libcam.halisp.utils \
    libcam.halisp.v4l2 \
    libcam.halsensor.hwintegration \
    libcam.halsensor \
    libcam.isptuning.v4l2 \
    libcam.peripheralcontroller \
    libcam.sensor_mode_helper \
    libcam.sensor_mode_helper_custom \
    libcam.tuningcachemgr \
    libcam.utils.sensorprovider \
    libcam.vhdr \
    libcam_ipc_hal3a_client \
    libcam_ipc_nvbuf_client \
    libcamalgo.BSSwrapper \
    libcamalgo.InlineCompGyro \
    libcamalgo.Mfbllwrapper \
    libcamalgo.aics \
    libcamalgo.ais2.bss \
    libcamalgo.ais2.mfnr \
    libcamalgo.bss \
    libcamalgo.c3d \
    libcamalgo.cac \
    libcamalgo.eis \
    libcamalgo.fsc \
    libcamalgo.fus \
    libcamalgo.gyro \
    libcamalgo.lmv \
    libcamalgo.lsc \
    libcamalgo.mcnr \
    libcamalgo.mfnr \
    libcamalgo.n3d \
    libcamalgo.platform2 \
    libcamalgo.rotate \
    libcamalgo.tsfs \
    libcamalgo.vaics \
    libcamalgo.vaidepth \
    libcamalgo.vsf \
    libcamera.custom.af_assist_buf_mgr \
    libcamera.custom.af_assist_buf_mgr_open \
    libcamera.custom.af_assist_mgr \
    libcamera.custom.af_assist_pdp \
    libcamera.customae \
    libcamera.customflk \
    libcameracustom.camera.3a \
    libcameracustom.camera.isp \
    libcameracustom.camera.sensors \
    libcameracustom.camera_calibration.core \
    libcameracustom.camera_exif \
    libcameracustom.cfg_setting.core \
    libcameracustom.eis \
    libcameracustom.flashlight \
    libcameracustom.imgsensor.core \
    libcameracustom.lens \
    libcameracustom.plugin \
    libcameracustom \
    libcameracustom_camera_db_ext \
    libccd \
    libdpframework \
    libeffecthal.base \
    libfacerelight \
    libfeature.aiseg \
    libfeature.face \
    libfeature.fwmvp \
    libfeature.mcnr \
    libfeature.stereo.platform \
    libfeature.stereo.provider \
    libfeature.vsdof.3a_info_provider \
    libfeature.vsdof.fd_info_provider \
    libfeature.vsdof.hal \
    libfeature.vsdof.nvram_provider \
    libfeature.vsdof.ot_info_provider \
    libfeature_eis \
    libfeature_fsc \
    libfeature_vrp \
    libfeatureiodrv_mem \
    libfeaturepolicy_dbhandler \
    libgpudataproducer \
    libimgstream-custom \
    libimgstream-drv \
    libimgstream-guard \
    libimgsys_adl \
    libimgsys_cmt \
    libimgsys_custom \
    libimgsys_daemon \
    libimgsys_dip \
    libimgsys_drvcommon \
    libimgsys_gce \
    libimgsys_main \
    libimgsys_me \
    libimgsys_pqdip \
    libimgsys_sensor \
    libimgsys_system \
    libimgsys_taskhandler \
    libimgsys_tdrhal \
    libimgsys_tile \
    libimgsys_traw \
    libimgsys_utils \
    libimgsys_v4l2 \
    libimgsys_wpe \
    libispfeature_mtkcam.v4l2 \
    libispinterpreter_mtkcam \
    liblpnr \
    libmfllcore \
    libmgr3a.adapt \
    libmmagent \
    libmml \
    libmmlpqImpl \
    libmtk_drvb \
    libmtkcam.atmseventmgr \
    libmtkcam.debugwrapper \
    libmtkcam.eventcallback \
    libmtkcam.featurepipe.capture \
    libmtkcam.featurepipe.depthmap \
    libmtkcam.featurepipe.p2g \
    libmtkcam.featurepipe.streaming \
    libmtkcam.featurepipe.vsdof.wrapper \
    libmtkcam.logicalcaminfoprovider \
    libmtkcam.logicalmodule \
    libmtkcam.ndd.limit \
    libmtkcam_aicolor \
    libmtkcam_aie \
    libmtkcam_android_zslprocessor \
    libmtkcam_aov \
    libmtkcam_aov_cust \
    libmtkcam_aov_plat \
    libmtkcam_aov_sys \
    libmtkcam_buffer_flush \
    libmtkcam_c2psperfctrl \
    libmtkcam_ca \
    libmtkcam_calibration_provider \
    libmtkcam_camcontroller \
    libmtkcam_camcoordinator \
    libmtkcam_camctrl \
    libmtkcam_camdeliver \
    libmtkcam_camsys_sensor_utils \
    libmtkcam_coredev \
    libmtkcam_custom.calibration_convertor \
    libmtkcam_custom.metadata \
    libmtkcam_custom.policy \
    libmtkcam_custom_sampleselector \
    libmtkcam_custom_zsdhdrselector \
    libmtkcam_custzone \
    libmtkcam_debugutils \
    libmtkcam_detectnode \
    libmtkcam_devicemgr \
    libmtkcam_diputils \
    libmtkcam_dma_map \
    libmtkcam_dpe_sp \
    libmtkcam_exif \
    libmtkcam_externalisploader \
    libmtkcam_faceResultHandler \
    libmtkcam_feature_utils \
    libmtkcam_grallocutils \
    libmtkcam_hal3a_provider \
    libmtkcam_hal_aidl_common \
    libmtkcam_hal_aidl_device \
    libmtkcam_hal_aidl_provider \
    libmtkcam_hal_aidl_utils \
    libmtkcam_hal_android_app_cbadaptor \
    libmtkcam_hal_android_common \
    libmtkcam_hal_android_device \
    libmtkcam_hal_android_provider \
    libmtkcam_hal_android_utils \
    libmtkcam_hal_aov \
    libmtkcam_hal_core_app \
    libmtkcam_hal_core_app_cbadaptor \
    libmtkcam_hal_core_device \
    libmtkcam_hal_core_devicesessionpolicy \
    libmtkcam_hal_core_featurepolicy \
    libmtkcam_hal_core_provider \
    libmtkcam_hal_core_utils \
    libmtkcam_hal_custom \
    libmtkcam_hal_custom_provider \
    libmtkcam_hal_hidl_common \
    libmtkcam_hal_hidl_device \
    libmtkcam_hal_hidl_provider \
    libmtkcam_hal_hidl_utils \
    libmtkcam_halisp_custom \
    libmtkcam_hwnode.jpegnode \
    libmtkcam_hwnode.p2 \
    libmtkcam_hwnode \
    libmtkcam_hwutils \
    libmtkcam_hwutils_android \
    libmtkcam_hwutils_poweronoffcontroller \
    libmtkcam_imgbuf_v2 \
    libmtkcam_ipc_core \
    libmtkcam_ipc_wrapper_common_client \
    libmtkcam_ipc_wrapper_common_server \
    libmtkcam_ipc_wrapper_mtk_client \
    libmtkcam_ipc_wrapper_mtk_server \
    libmtkcam_jsonconvertor \
    libmtkcam_jsondata \
    libmtkcam_mapping_mgr \
    libmtkcam_metaconv \
    libmtkcam_metadata \
    libmtkcam_metastore \
    libmtkcam_modulefactory_custom \
    libmtkcam_modulefactory_utils \
    libmtkcam_modulehelper \
    libmtkcam_p1node \
    libmtkcam_packutils \
    libmtkcam_perfctrl \
    libmtkcam_pip \
    libmtkcam_pipeline \
    libmtkcam_pipeline_fbm \
    libmtkcam_pipelinemodel_capture \
    libmtkcam_pipelinemodel_session \
    libmtkcam_pipelinemodel_utils \
    libmtkcam_pipelinepolicy-security \
    libmtkcam_pipelinepolicy-smvr \
    libmtkcam_pipelinepolicy \
    libmtkcam_pipelinepolicy_factory \
    libmtkcam_pipemgr \
    libmtkcam_postprocprovider \
    libmtkcam_preprocnode \
    libmtkcam_prerelease \
    libmtkcam_proc \
    libmtkcam_request_requlator \
    libmtkcam_resourcedecision \
    libmtkcam_resourcedecision_custom \
    libmtkcam_salmgr \
    libmtkcam_sensorcontrol \
    libmtkcam_simager \
    libmtkcam_smvr \
    libmtkcam_stdutils \
    libmtkcam_streamutils \
    libmtkcam_synchelper \
    libmtkcam_sysutils \
    libmtkcam_taskmgr \
    libmtkcam_thirdparty.core \
    libmtkcam_thirdparty.customer \
    libmtkcam_thirdparty.customzone \
    libmtkcam_thirdparty.mtk \
    libmtkcam_thirdparty \
    libmtkcam_tuning_utils \
    libmtkcam_ulog \
    libmtkcam_zsl_customselector \
    libmtkcm_ipc_dummy \
    libmtkltm \
    libneuralnetworks_sl_driver_mtk_prebuilt \
    libneuron_adapter_mgvi \
    libneuron_runtime.7 \
    libneuron_runtime \
    libneuron_wrapper \
    libnir_neon_driver \
    libnpgetfilepath \
    libpda_usdriver \
    libpq_cust_base \
    libpq_sec \
    libpqconfig \
    libpqparamparser \
    libvainr_model \
    mtk000_mipi_raw_IdxMgr \
    mtk000_mipi_raw_tuning \
    ov13b10_mipi_raw_IdxMgr \
    ov13b10_mipi_raw_tuning \
    s5k4h7_mipi_raw_IdxMgr \
    s5k4h7_mipi_raw_tuning \
    sc820cs_mipi_raw_IdxMgr \
    sc820cs_mipi_raw_tuning \
    vendor.lenovo.hardware.display-V1-ndk \
    vendor.mediatek.hardware.apuware.apusys-V3-ndk \
    vendor.mediatek.hardware.apuware.utils-V1-ndk-vendor \
    vendor.mediatek.hardware.apuware.utils@2.0-vendor \
    vendor.mediatek.hardware.audio@8.1 \
    vendor.mediatek.hardware.bluetooth.audio-V1-ndk \
    vendor.mediatek.hardware.bluetooth.audio@2.1 \
    vendor.mediatek.hardware.bluetooth.audio@2.2 \
    vendor.mediatek.hardware.camera.aovservice-V2-ndk \
    vendor.mediatek.hardware.camera.atms-V1-ndk \
    vendor.mediatek.hardware.camera.bgservice-V1-ndk \
    vendor.mediatek.hardware.camera.ccap@1.0 \
    vendor.mediatek.hardware.camera.frhandler@1.0 \
    vendor.mediatek.hardware.camera.isphal-V1-ndk \
    vendor.mediatek.hardware.camera.postproc@1.0 \
    vendor.mediatek.hardware.camera.security@1.0 \
    vendor.mediatek.hardware.composer_ext-V1-ndk \
    vendor.mediatek.hardware.composer_ext@1.0 \
    vendor.mediatek.hardware.mmagent-V1-ndk \
    vendor.mediatek.hardware.mmlpq-V3-ndk \
    vendor.mediatek.hardware.mtkpower-V1-ndk \
    vendor.mediatek.hardware.neuropilot.agent-V1-ndk \
    vendor.mediatek.hardware.neuropilot.agent@1.0 \
    vendor.mediatek.hardware.neuropilot.agent@1.1 \
    vendor.mediatek.hardware.neuropilot.agent@1.2 \
    vendor.mediatek.hardware.nvram-V1-ndk \
    vendor.mediatek.hardware.power@1.1 \
    vendor.mediatek.hardware.power@2.0 \
    vendor.mediatek.hardware.pq_aidl-V2-ndk \
    vendor.mediatek.hardware.pq_aidl-V4-ndk \
    vendor.mediatek.hardware.pq_aidl-V7-ndk \
    wechat.beanpod \
    libapu_mdw_ext.mtk \
    libapuwareapusys.mtk \
    libapuwareapusys_v2.mtk \
    libapuwarehmp.mtk \
    libapuwareutils.mtk \
    libapuwareutils_v2.mtk \
    libapuwarexrp.mtk \
    libapuwarexrp_v2.mtk \
    libarmnn_ndk.mtk \
    libcmdl_ndk.mtk \
    libmvpu_cic_ci_compiler.mtk \
    libmvpu_cic_ci_compiler_25.mtk \
    libmvpu_clc_14_mvpu_debuginfo_25.mtk \
    libmvpu_clc_14_mvpu_elf_25.mtk \
    libmvpu_clc_14_mvpu_utility_25.mtk \
    libmvpu_clc_mvpu_debuginfo.mtk \
    libmvpu_clc_mvpu_elf.mtk \
    libmvpu_clc_mvpu_utility.mtk \
    libmvpu_config.mtk \
    libmvpu_engine.mtk \
    libmvpu_engine_25.mtk \
    libmvpu_engine_25_pub.mtk \
    libmvpu_engine_pub.mtk \
    libmvpu_pattern.mtk \
    libmvpu_pattern_25.mtk \
    libmvpu_pattern_25_pub.mtk \
    libmvpu_pattern_pub.mtk \
    libmvpu_runtime.mtk \
    libmvpu_runtime_25.mtk \
    libmvpu_runtime_25_pub.mtk \
    libmvpu_runtime_builtin.mtk \
    libmvpu_runtime_builtin_25.mtk \
    libmvpu_runtime_pub.mtk \
    libmvpuop25_mtk_cv.mtk \
    libmvpuop25_mtk_nn.mtk \
    libmvpuop_mtk_cv.mtk \
    libmvpuop_mtk_nn.mtk \
    libneuron_graph_delegate.mtk \
    libneuronusdk_adapter.mtk \
    libnir_neon_driver_ndk.mtk \
    libtflite_mtk.mtk \
    libtflite_mtk \
    vendor.mediatek.hardware.apuware.apusys-V5-ndk \
    vendor.mediatek.hardware.apuware.apusys@1.0 \
    vendor.mediatek.hardware.apuware.apusys@2.0 \
    vendor.mediatek.hardware.apuware.apusys@2.1 \
    vendor.mediatek.hardware.apuware.hmp@1.0 \
    vendor.mediatek.hardware.apuware.utils-V1-ndk \
    vendor.mediatek.hardware.apuware.utils@1.0 \
    vendor.mediatek.hardware.apuware.utils@2.0 \
    vendor.mediatek.hardware.apuware.xrp-V1-ndk \
    vendor.mediatek.hardware.apuware.xrp@1.0 \
    vendor.mediatek.hardware.apuware.xrp@2.0 \
    com.google.android.widevine.nonupdatable \
    HotwordEnrollmentOKGoogleRISCV \
    HotwordEnrollmentXGoogleRISCV \
    com.android.hotwordenrollment.common.util \
    android.hardware.gatekeeper-service.beanpod.xml \
    android.hardware.neuralnetworks-shim-service-mtk.xml \
    android.hardware.security.keymint-service.beanpod.xml \
    android.hardware.security.secureclock-service.beanpod.xml \
    android.hardware.security.sharedsecret-service.beanpod.xml \
    bluetooth_audio.xml \
    manifest_allocator.xml \
    manifest_apuware_apusys_aidl.xml \
    manifest_apuware_utils_aidl.xml \
    manifest_cameraprovider.xml \
    manifest_hwcomposer.xml \
    manifest_isphal.xml \
    manifest_media_c2_V1_2_default.xml \
    manifest_mmlpq.xml \
    mapper.mediatek.xml \
    bp_kmsetkey_ca \
    chipinfo \
    conninfra_loader \
    fuelgauged \
    fuelgauged_nvram \
    android.hardware.gatekeeper-service.beanpod \
    android.hardware.graphics.composer@3.2-service \
    android.hardware.media.c2@1.2-mediatek-64b \
    android.hardware.neuralnetworks-shim-service-mtk \
    android.hardware.security.keymint@3.0-service.beanpod \
    android.hardware.graphics.allocator-V2-service-mediatek.mt6897 \
    camerahalserver \
    tetheroffloadservice \
    vendor.lenovo.hardware.display-service \
    vendor.mediatek.hardware.mmagent-service \
    vendor.mediatek.hardware.mmlpq@V1-service \
    vendor.mediatek.hardware.nvram-service \
    vendor.mediatek.hardware.pq_aidl-service \
    init.insmod \
    nvram_daemon \
    teei_daemon \
    wlan_assistant

PRODUCT_PACKAGES += \
    vendor_bin_crossbuild_DataSet_SQLiteModule_db_ae_ParameterDB_ae_db \
    vendor_bin_crossbuild_DataSet_SQLiteModule_db_af_ParameterDB_af_db \
    vendor_bin_crossbuild_DataSet_SQLiteModule_db_awb_ParameterDB_awb_db \
    vendor_bin_crossbuild_DataSet_SQLiteModule_db_awbsync_ParameterDB_awbsync_db \
    vendor_bin_crossbuild_DataSet_SQLiteModule_db_feature_ParameterDB_feature_db \
    vendor_bin_crossbuild_DataSet_SQLiteModule_db_flash_ParameterDB_flash_db \
    vendor_bin_crossbuild_DataSet_SQLiteModule_db_flashcali_ParameterDB_flashcali_db \
    vendor_bin_crossbuild_DataSet_SQLiteModule_db_ParameterDB_db \
    vendor_bin_crossbuild_DataSet_SQLiteModule_db_sw_top_control_data_db \
    vendor_bin_crossbuild_DataSet_SQLiteModule_db_top_control_data_db \
    vendor_bin_crossbuild_DataSet_SQLiteModule_db_pd_ParameterDB_pd_db \
    vendor_bin_crossbuild_DataSet_SQLiteModule_db_pipeline_ParameterDB_pipeline_db \
    vendor_bin_crossbuild_DataSet_SQLiteModule_db_port_select_db \
    vendor_bin_crossbuild_DataSet_SQLiteModule_db_tone_ParameterDB_tone_db \
    vendor_bin_crossbuild_DataSet_SQLiteModule_db_tuning_DB_default_sensor_ISP_mapping_db \
    vendor_bin_crossbuild_DataSet_SQLiteModule_db_tuning_DB_default_sensor_ISP_param_db \
    vendor_bin_crossbuild_DataSet_SQLiteModule_db_tuning_DB_gc13a0_mipi_raw_ISP_mapping_db \
    vendor_bin_crossbuild_DataSet_SQLiteModule_db_tuning_DB_gc13a0_mipi_raw_ISP_param_db \
    vendor_bin_crossbuild_DataSet_SQLiteModule_db_tuning_DB_imx214_mipi_raw_ISP_mapping_db \
    vendor_bin_crossbuild_DataSet_SQLiteModule_db_tuning_DB_imx214_mipi_raw_ISP_param_db \
    vendor_bin_crossbuild_DataSet_SQLiteModule_db_tuning_DB_imx334_mipi_raw_ISP_mapping_db \
    vendor_bin_crossbuild_DataSet_SQLiteModule_db_tuning_DB_imx334_mipi_raw_ISP_param_db \
    vendor_bin_crossbuild_DataSet_SQLiteModule_db_tuning_DB_imx334sub_mipi_raw_ISP_mapping_db \
    vendor_bin_crossbuild_DataSet_SQLiteModule_db_tuning_DB_imx334sub_mipi_raw_ISP_param_db \
    vendor_bin_crossbuild_DataSet_SQLiteModule_db_tuning_DB_imx481_mipi_raw_ISP_mapping_db \
    vendor_bin_crossbuild_DataSet_SQLiteModule_db_tuning_DB_imx481_mipi_raw_ISP_param_db \
    vendor_bin_crossbuild_DataSet_SQLiteModule_db_tuning_DB_imx499_mipi_raw_ISP_mapping_db \
    vendor_bin_crossbuild_DataSet_SQLiteModule_db_tuning_DB_imx499_mipi_raw_ISP_param_db \
    vendor_bin_crossbuild_DataSet_SQLiteModule_db_tuning_DB_imx586_mipi_raw_ISP_mapping_db \
    vendor_bin_crossbuild_DataSet_SQLiteModule_db_tuning_DB_imx586_mipi_raw_ISP_param_db \
    vendor_bin_crossbuild_DataSet_SQLiteModule_db_tuning_DB_imx709_mipi_raw_ISP_mapping_db \
    vendor_bin_crossbuild_DataSet_SQLiteModule_db_tuning_DB_imx709_mipi_raw_ISP_param_db \
    vendor_bin_crossbuild_DataSet_SQLiteModule_db_tuning_DB_imx709o_mipi_raw_ISP_mapping_db \
    vendor_bin_crossbuild_DataSet_SQLiteModule_db_tuning_DB_imx709o_mipi_raw_ISP_param_db \
    vendor_bin_crossbuild_DataSet_SQLiteModule_db_tuning_DB_imx766_mipi_raw_ISP_mapping_db \
    vendor_bin_crossbuild_DataSet_SQLiteModule_db_tuning_DB_imx766_mipi_raw_ISP_param_db \
    vendor_bin_crossbuild_DataSet_SQLiteModule_db_tuning_DB_imx766dual_mipi_raw_ISP_mapping_db \
    vendor_bin_crossbuild_DataSet_SQLiteModule_db_tuning_DB_imx766dual_mipi_raw_ISP_param_db \
    vendor_bin_crossbuild_DataSet_SQLiteModule_db_tuning_DB_imx766dualo_mipi_raw_ISP_mapping_db \
    vendor_bin_crossbuild_DataSet_SQLiteModule_db_tuning_DB_imx766dualo_mipi_raw_ISP_param_db \
    vendor_bin_crossbuild_DataSet_SQLiteModule_db_tuning_DB_imx766o_mipi_raw_ISP_mapping_db \
    vendor_bin_crossbuild_DataSet_SQLiteModule_db_tuning_DB_imx766o_mipi_raw_ISP_param_db \
    vendor_bin_crossbuild_DataSet_SQLiteModule_db_tuning_DB_imx866_mipi_raw_ISP_mapping_db \
    vendor_bin_crossbuild_DataSet_SQLiteModule_db_tuning_DB_imx866_mipi_raw_ISP_param_db \
    vendor_bin_crossbuild_DataSet_SQLiteModule_db_tuning_DB_imx989_mipi_raw_ISP_mapping_db \
    vendor_bin_crossbuild_DataSet_SQLiteModule_db_tuning_DB_imx989_mipi_raw_ISP_param_db \
    vendor_bin_crossbuild_DataSet_SQLiteModule_db_tuning_DB_ISP_info_db \
    vendor_bin_crossbuild_DataSet_SQLiteModule_db_tuning_DB_ov13b10_mipi_raw_ISP_mapping_db \
    vendor_bin_crossbuild_DataSet_SQLiteModule_db_tuning_DB_ov13b10_mipi_raw_ISP_param_db \
    vendor_bin_crossbuild_DataSet_SQLiteModule_db_tuning_DB_ov48b_mipi_raw_ISP_mapping_db \
    vendor_bin_crossbuild_DataSet_SQLiteModule_db_tuning_DB_ov48b_mipi_raw_ISP_param_db \
    vendor_bin_crossbuild_DataSet_SQLiteModule_db_tuning_DB_s5k3m5sx_mipi_raw_ISP_mapping_db \
    vendor_bin_crossbuild_DataSet_SQLiteModule_db_tuning_DB_s5k3m5sx_mipi_raw_ISP_param_db \
    vendor_bin_crossbuild_DataSet_SQLiteModule_db_tuning_DB_s5k3m5sxo_mipi_raw_ISP_mapping_db \
    vendor_bin_crossbuild_DataSet_SQLiteModule_db_tuning_DB_s5k3m5sxo_mipi_raw_ISP_param_db \
    vendor_bin_crossbuild_DataSet_SQLiteModule_db_tuning_DB_s5k3p9sp_mipi_raw_ISP_mapping_db \
    vendor_bin_crossbuild_DataSet_SQLiteModule_db_tuning_DB_s5k3p9sp_mipi_raw_ISP_param_db \
    vendor_bin_crossbuild_DataSet_SQLiteModule_db_tuning_DB_s5k4h7_mipi_raw_ISP_mapping_db \
    vendor_bin_crossbuild_DataSet_SQLiteModule_db_tuning_DB_s5k4h7_mipi_raw_ISP_param_db \
    vendor_bin_crossbuild_DataSet_SQLiteModule_db_tuning_DB_sc820cs_mipi_raw_ISP_mapping_db \
    vendor_bin_crossbuild_DataSet_SQLiteModule_db_tuning_DB_sc820cs_mipi_raw_ISP_param_db \
    vendor_bin_crossbuild_DataSet_SQLiteModule_db_tuning_DB_aov_default_sensor_ISP_mapping_db \
    vendor_bin_crossbuild_DataSet_SQLiteModule_db_tuning_DB_aov_default_sensor_ISP_param_db \
    vendor_bin_crossbuild_DataSet_SQLiteModule_db_tuning_DB_aov_ISP_info_db \
    vendor_bin_hw_android_hardware_graphics_allocator-V2-service-mediatek \
    vendor_bin_hw_camerahalserver \
    vendor_lib64_egl_libGLES_mali_so \
    vendor_lib64_hw_audio_primary_mt6897_so \
    vendor_lib64_hw_android_hardware_graphics_allocator-V2-mediatek_so \
    vendor_lib64_hw_android_hardware_graphics_mapper@4_0-impl-mediatek_so \
    vendor_lib64_hw_mapper_mediatek_so \
    vendor_lib64_hw_vendor_mediatek_hardware_pq_aidl-impl_so \
    vendor_lib64_hw_vulkan_mali_so \
    vendor_lib64_hw_sensors_mt6897_so \
    vendor_lib64_arm_graphics-V4-ndk_so \
    vendor_lib64_arm_mali_platform-V2-ndk_so \
    vendor_lib64_libaal_cust_func_so \
    vendor_lib64_libaalservice_so \
    vendor_lib64_libaiselector_so \
    vendor_lib64_libapudcutils_so \
    vendor_lib64_libdpframework_so \
    vendor_lib64_libmmagent_so \
    vendor_lib64_libmml_so \
    vendor_lib64_libmmlpqImpl_so \
    vendor_lib64_libneuralnetworks_sl_driver_mtk_prebuilt_so \
    vendor_lib64_libneuron_adapter_mgvi_so \
    vendor_lib64_libneuron_runtime_7_so \
    vendor_lib64_libneuron_runtime_so \
    vendor_lib64_libneuron_wrapper_so \
    vendor_lib64_libnir_neon_driver_so \
    vendor_lib64_libpq_cust_base_so \
    vendor_lib64_libpq_sec_so \
    vendor_lib64_libpqconfig_so \
    vendor_lib64_libpqparamparser_so
